__title__ = 'topic_analysis'
__version__ = '0.1.0'
__summary__ = 'Topic analysis library'
__uri__ = 'https://github.com/surajiyer/topic_analysis'
__author__ = 'Suraj Iyer'
__email__ = 'me@surajiyer.com'
__license__ = 'MIT'